language: java
jdk:
- openjdk8

install: "./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dfindbus.skip=true -Dcheckstyle.skip=true -B -V"

script: "./mvnw clean test -B"

cache:
  directories:
  - "$HOME/.m2"
